IHub-218462 Delete files from the archive after a specified number of days
ov-integrations/sftp-to-efile pull request #4
Opened 2022-10-24 13:30 UTC by P4radise

[IHub-218462](https://trackor.onevizion.com/form/ConfigAppForm.do?id=100107228562&ttid=10009161) Delete files from the archive after a specified number of days

[IHub-218462-103098](https://trackor.onevizion.com/form/ConfigAppForm.do?id=100107239838&ttid=100091445) amoiseenko (Andrey Moiseenko)
[IHub-218462-103100](https://trackor.onevizion.com/form/ConfigAppForm.do?id=100107239839&ttid=100091445) vadim.glebov (Vadim Glebov)
[IHub-218462-103206](https://trackor.onevizion.com/form/ConfigAppForm.do?id=100107240411&ttid=100091445) iemelyanov (Ilya Emelyanov)

2022-10-24 13:31 UTC, P4radise commented
This review is related to the comments in this review https://github.com/ov-integrations/sftp-to-efile/pull/3

2022-10-25 04:30 UTC, glebowadim requested changes

2022-10-25 04:30 UTC, glebowadim commented on module.py
> +        self.delete_file(sftp, file_name)
Actually it is not just ```delete_file()```. It's ```delete_file_from_archive()```
Maybe we should rename it?
It's strange that we first delete the file and then move it.

2022-10-25 08:34 UTC, P4radise commented on module.py
> +        self.delete_file(sftp, file_name)
I added one more variable to the delete_file procedure - directory - now it should be more logical.

About removing the file before moving it to the archive - I added a check to find the file in the archive, if it exists - it will be removed and then moved. If it's not found, it will be immediately moved to the archive.

2022-10-25 17:01 UTC, glebowadim approved these changes

2022-10-26 13:54 UTC, merged